---

  - name: Add nodes to host file
    lineinfile:
      path: /etc/hosts
      line: "{{ item.ip }} {{ item.name }}"
      create: yes
    loop: "{{ nodes }}"

  - name: Install K3S
    shell:
      cmd: /tmp/install-k3s.sh --docker
      args:
        executable: /bin/bash

  - name: Give Docker ownership of k3s config
    file:
      path: /etc/rancher/k3s/k3s.yaml
      owner: docker
      mode: g+r