---

  - name: Install dependencies
    package:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present
  
  - name: Check if keyring directory exists
    stat:
      path: /etc/apt/keyrings
    register: dir_data

  - name: Directory exists skipping creation
    debug:
      msg: "Apt keyrings directory already exists, skipping creation"
    when: dir_data.stat.exists

  - name: Create apt keyring directory
    file:
      path: /etc/apt/keyrings
      state: directory
    when: not dir_data.stat.exists

  - name: Check if Docker repository GPG key is present
    stat:
      path: /etc/apt/keyrings/docker.gpg
    register: gpg_data

  - name: GPG key exists skipping download
    debug:
      msg: "GPG key prevously downloaded, skipping download"
    when: gpg_data.stat.exists

  - name: Get Docker repository GPG key
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings
    when: not gpg_data.stat.exists

  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  {{ ansible_distribution_release }} stable"
      state: present

  - name: Install or update Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest

  - name: Check if k3s installer is present
    stat:
      path: /tmp/install-k3s.sh
    register: file_data

  - name: File exists skipping download
    debug:
      msg: "Installer previously downloaded, skipping download"
    when: file_data.stat.exists

  - name: Download k3s installer
    get_url:
      url: https://get.k3s.io
      dest: /tmp/install-k3s.sh
      mode: '0644'
    when: not file_data.stat.exists

  - name: Make k3s installer executable
    file:
      path: /tmp/install-k3s.sh
      mode: a+x